# Generated by Django 5.0.7 on 2024-07-27 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_alter_item_options_remove_item_image_itemphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='itemphoto',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='item.item'),
        ),
    ]
