# Generated by Django 5.0.7 on 2024-07-27 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_alter_itemphoto_image_alter_itemphoto_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemphoto',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='item.itemphoto'),
        ),
    ]
